/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import PacoteAluno.InterfaceLista;
import PacoteAluno.Aluno;
//import PacoteAluno.AlunoBD;
import PacoteAluno.RemocaoAlunoDAO;
import java.util.ArrayList;
import java.util.List;
//import javax.persistence.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author soare
 */
public class TelaPesquisa extends javax.swing.JFrame{
    private List<Aluno> listaDeAlunos = new ArrayList<>();
    private Aluno aluno;
    //private EntityManagerFactory entityManagerFactory = Persistence.createEntityManagerFactory("com.mycompany_Alunos_jar_1.0-SNAPSHOTPU");
    //private EntityManager entityManager = entityManagerFactory.createEntityManager();

    /**
     * Creates new form TelaPesquisa
     * @param ListaDeAlunos
     */
    public TelaPesquisa(List<Aluno> ListaDeAlunos) {
        this.listaDeAlunos = ListaDeAlunos;
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setTitle("Tela De Pesquisa");
    }
    
    public TelaPesquisa(List<Aluno> ListaDeAlunos, String botao) {
        this.listaDeAlunos = ListaDeAlunos;
        initComponents();
        bntPesquisar.setText(botao);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setTitle("Excluir aluno da lista");
    }
    
    public TelaPesquisa(List<Aluno> ListaDeAlunos, Aluno aluno) {
        this.listaDeAlunos = ListaDeAlunos;
        this.aluno = aluno;
        initComponents();
        bntPesquisar.setText("Inserir");
        txtCable.setText("Insira a posição:");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setTitle("Inserir na posição");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bntPesquisar = new javax.swing.JButton();
        txtCable = new javax.swing.JLabel();
        txtMat = new javax.swing.JTextField();
        bntSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bntPesquisar.setText("Pesquisar");
        bntPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPesquisarActionPerformed(evt);
            }
        });

        txtCable.setText("Insira a matricula:");

        bntSair.setText("Sair");
        bntSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(txtCable))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bntPesquisar)
                                .addGap(18, 18, 18)
                                .addComponent(bntSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtMat, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(txtCable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMat, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntPesquisar)
                    .addComponent(bntSair))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPesquisarActionPerformed
        if(bntPesquisar.getText().equals("Excluir")){
            for (Aluno a: listaDeAlunos){
                if(a.getMat().equals(txtMat.getText())){
                    //excluirAlunoBD(txtMat.getText());
                    RemocaoAlunoDAO removeAluno =  new RemocaoAlunoDAO();
                    setListaDeAlunos(removeAluno.removerAluno(listaDeAlunos, a));
                    JOptionPane.showMessageDialog(this, "Aluno excluido com sucesso!");
                    return;
                }
            }
            JOptionPane.showMessageDialog(this, "Aluno não encontrado!");
        }else if(bntPesquisar.getText().equals("Inserir")){
            try{
                if(txtMat.getText().equals("0")){
                    throw new NumberFormatException();
                }else{
                    listaDeAlunos = inserePos(listaDeAlunos, aluno, txtMat.getText());
                    JOptionPane.showMessageDialog(this, "Dados salvos com sucesso!");
                }
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Insira um número maior que zero!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            String mat = txtMat.getText();
            InterfaceLista InterfaceLista = new InterfaceLista(listaDeAlunos, mat);
            InterfaceLista.setVisible(true);  
          }
    
    }//GEN-LAST:event_bntPesquisarActionPerformed

    private void bntSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSairActionPerformed
        dispose();
    }//GEN-LAST:event_bntSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TelaPesquisa().setVisible(true);
            }
        });
    }
    public List<Aluno> getListaDeAlunos (){
        return listaDeAlunos;
    }
    public void setListaDeAlunos(List<Aluno> alunos){
        this.listaDeAlunos = alunos;
    }
    
    public List<Aluno> inserePos(List<Aluno> alunos, Aluno a, String pos){
        int num = Integer.parseInt(pos);
        num = num - 1;
        alunos.add(num, a);
        return alunos;
    }
    
    /*private void excluirAlunoBD(String mat){
        AlunoBD alunobd = entityManager.find(AlunoBD.class, mat);
        entityManager.getTransaction().begin();
        entityManager.remove(alunobd);
        entityManager.getTransaction().commit();
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntPesquisar;
    private javax.swing.JButton bntSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtCable;
    private javax.swing.JTextField txtMat;
    // End of variables declaration//GEN-END:variables
}
